version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
    config:
      languages:
        javascript:
          threshold: 350
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
    config:
      threshold: 200
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: false
  identical-code:
    enabled: true
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  stylelint:
    enabled: true
    exclude_patterns:
    - "public/"
    - "yarn.lock"
  duplication:
    enabled: true
    exclude_patterns:
      - "spec"
    config:
      languages:
        - ruby
  rubocop:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-4
    config:
      config: .eslintrc-codeclimate.js
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
  flog:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-48
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
    issue_override:
      severity: major
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "app/assets"
